import Footer from "@/components/layout/footer/Footer";
import Header from "@/components/layout/header/Header";

export const metadata = {
  title: {
    absolute: "",
    default: "company name",
    template: "%s | company name",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({children}) {
  return (
    <>
      <Header />
      <>{children}</>
      <Footer />
    </>
  );
}
